apiVersion: v1
kind: Service
metadata:
  name: {{ include "mill-game.fullname" . }}-service
  namespace: {{ .Chart.Name }}
  labels:
    {{- include "mill-game.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "mill-game.selectorLabels" . | nindent 4 }}
