apiVersion: v1
kind: Namespace
metadata:
  name: mill-app
---
apiVersion: v1
kind: Service
metadata:
  name: mill-app-service
  namespace: mill-app
  labels:
    app: mill-app
spec:
  type: LoadBalancer
  selector:
    app: mill-app
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mill-app-ingress
  namespace: mill-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mill-app-service
            port:
              number: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mill-app-deployment
  namespace: mill-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mill-app
  template:
    metadata:
      labels:
        app: mill-app
    spec:
      containers:
        - name: mill-app
          image: <your-repository>
          ports:
          - containerPort: 80
